CREATE OR REPLACE
PROCEDURE MUEVE_FAMILIA(ID_FAMILIA_ORIGEN NUMBER, ID_FAMILIA_DESTINO NUMBER)
IS

	--DECLARACIÓN DE VARIABLES
	RESULTADO BOOLEAN;
	PADRE NUMBER;
	TYPE CURSOR_FAMILIAS IS REF CURSOR RETURN FAMILIAS%ROWTYPE;
	CFAMILIAS CURSOR_FAMILIAS;
	FAMILIA CFAMILIAS%ROWTYPE;
	EXISTE_F_ORIGEN BOOLEAN;
	EXISTE_F_DESTINO BOOLEAN;

	--FUNCIÓN QUE COMPRUEBA SI LA FAMILIA DESTINO ES HIJA DE LA FAMILIA ORIGEN
	FUNCTION COMPRUEBA_SI_ES_HIJA(ID_F_ORIGEN NUMBER, ID_F_DESTINO NUMBER) 
		RETURN BOOLEAN IS ES_HIJA BOOLEAN;
		BEGIN
		SELECT FAMILIA INTO PADRE FROM FAMILIAS WHERE IDENTIFICADOR = ID_F_DESTINO;
		IF PADRE IS NULL THEN
			RETURN FALSE;
		ELSE
			IF PADRE = ID_F_ORIGEN THEN
				RETURN TRUE;
			ELSE
				RETURN COMPRUEBA_SI_ES_HIJA (ID_F_ORIGEN, PADRE);
			END IF;
		END IF;
	END COMPRUEBA_SI_ES_HIJA;
	
BEGIN

	--HABILITO SALIDA PARA DEBUG
	DBMS_OUTPUT.ENABLE( 1000000 );

	--COMPRUEBO SI EXISTE LA FAMILIA ORIGEN
	EXISTE_F_ORIGEN := TRUE;
	OPEN CFAMILIAS FOR SELECT * FROM FAMILIAS WHERE IDENTIFICADOR = ID_FAMILIA_ORIGEN;
	FETCH CFAMILIAS INTO FAMILIA;
	IF CFAMILIAS%NOTFOUND THEN
		DBMS_OUTPUT.PUT_LINE('LA FAMILIA ORIGEN NO EXISTE');
		EXISTE_F_ORIGEN := FALSE;
	END IF;
	CLOSE CFAMILIAS;

	--COMPRUEBO SI EXISTE LA FAMILIA DESTINO
	EXISTE_F_DESTINO := TRUE;
	OPEN CFAMILIAS FOR SELECT * FROM FAMILIAS WHERE IDENTIFICADOR = ID_FAMILIA_DESTINO;
	FETCH CFAMILIAS INTO FAMILIA;
	IF CFAMILIAS%NOTFOUND THEN
		DBMS_OUTPUT.PUT_LINE('LA FAMILIA DESTINO NO EXISTE');
		EXISTE_F_DESTINO := FALSE;
	END IF;
	CLOSE CFAMILIAS;

	--SI EXISTE TANTO LA FAMILIA ORIGEN COMO LA DESTINO CONTINÚO CON EL RESTO DE ACCIONES
	IF EXISTE_F_ORIGEN = TRUE AND EXISTE_F_DESTINO = TRUE THEN
	
		--COMPRUEBO QUE LA FAMILIA DESTINO NO SEA YA HIJA DE LA FAMILIA ORIGEN
		RESULTADO := COMPRUEBA_SI_ES_HIJA(ID_FAMILIA_ORIGEN, ID_FAMILIA_DESTINO);
		IF RESULTADO = TRUE THEN
			DBMS_OUTPUT.PUT_LINE('FAMILIA DESTINO ES HIJA DE FAMILIA ORIGEN. NO SE PODRÁ REALIZAR EL PROCESO');
		ELSE
			--CONTINÚO CON EL PROCESO
			DBMS_OUTPUT.PUT_LINE('REALIZADO EL PROCESO DE REASIGNACIÓN.');
			UPDATE FAMILIAS SET FAMILIA = ID_FAMILIA_DESTINO, OFICINA = NULL WHERE IDENTIFICADOR = ID_FAMILIA_ORIGEN;
			COMMIT;
		END IF;
		
	END IF;

END;
/

